specVersion: 1.0.0
name: testnet-subql-uniqueone
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: ">=1.13.3"
  query:
    name: "@subql/query"
    version: "*"
description: This project can be use as a starting po...
repository: https://github.com/octopus-appchains/testnet-subql-uniqueone.git
schema:
  file: ./schema.graphql
network:
  endpoint: >-
    wss://gateway.testnet.octopus.network/uniqueone/e83rnqoi4hr65cwx46a83u6a7a970dgq
  genesisHash: "0x9b834b6f1a2d1fd3fc702fdf76f26c785540dfd2089a00fc7e6d98ecfdb027fd"
dataSources:
  - kind: substrate/Runtime
    startBlock: 300000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler