specVersion: 0.2.0
name: testnet-subql-uniqueone
version: 0.0.4
description: This project can be use as a starting po...
repository: https://github.com/octopus-appchains/testnet-subql-uniqueone.git
schema:
  file: ./schema.graphql
network:
  endpoint: >-
    wss://gateway.testnet.octopus.network/uniqueone/e83rnqoi4hr65cwx46a83u6a7a970dgq
  genesisHash: "0x10bfb9af1771fb58841d86209cc7e2055179d34b1aecddce4d45f5f793c02d83"
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
        - handler: systemTokenTransferEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
